set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif

" Vundle
set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=$XDG_DATA_HOME/Vundle.vim
call vundle#rc("$XDG_DATA_HOME/Vundle.vim/bundle")
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'itchyny/lightline.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'tomasiser/vim-code-dark'

call vundle#end()

" lightline
set laststatus=2

syntax on
:set mouse=a

colorscheme codedark

" Wrap gitcommit file types at the appropriate length
filetype indent plugin on

autocmd BufEnter COMMIT_EDITMSG setlocal colorcolumn=+1

" spelling
:set spell
:iabbrev amoutn amount
:iabbrev becasue because
:iabbrev notificatiosn notifications
:iabbrev odcument document
:iabbrev odcuments documents
:iabbrev trasnaction transaction
