repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
        exclude: 'templates/Code/User/keybindings\.json'
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-toml
    -   id: check-yaml
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
    -   id: pretty-format-json
        args: [--autofix]
        exclude: 'templates/Code/User/keybindings\.json'
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/samueljsb/sort-lines
    rev: v0.3.0
    hooks:
    -   id: sort-lines
        args: [--case-insensitive]
-   repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
    -   id: check-json5
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.16.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/PyCQA/flake8
    rev: '7.3.0'
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear]
