start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

on-focus-changed = ['move-mouse window-lazy-center']
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-ctrl-1 = 'workspace 1'
alt-ctrl-2 = 'workspace 2'
alt-ctrl-3 = 'workspace 3'
alt-ctrl-4 = 'workspace 4'
alt-ctrl-5 = 'workspace 5'
alt-ctrl-6 = 'workspace 6'
alt-ctrl-7 = 'workspace 7'
alt-ctrl-8 = 'workspace 8'
alt-ctrl-9 = 'workspace 9'
alt-z = 'workspace Z'  # main workspace
alt-a = 'workspace A'  # alternative (secondary)
alt-w = 'workspace W'  # web browser
alt-t = 'workspace T'  # notes
alt-m = 'workspace M'  # meetings
alt-g = 'workspace G'  # Toggl or other tracking

ctrl-alt-cmd-1 = 'move-node-to-workspace 1'
ctrl-alt-cmd-2 = 'move-node-to-workspace 2'
ctrl-alt-cmd-3 = 'move-node-to-workspace 3'
ctrl-alt-cmd-4 = 'move-node-to-workspace 4'
ctrl-alt-cmd-5 = 'move-node-to-workspace 5'
ctrl-alt-cmd-6 = 'move-node-to-workspace 6'
ctrl-alt-cmd-7 = 'move-node-to-workspace 7'
ctrl-alt-cmd-8 = 'move-node-to-workspace 8'
ctrl-alt-cmd-9 = 'move-node-to-workspace 9'
ctrl-alt-cmd-z = 'move-node-to-workspace Z'
ctrl-alt-cmd-a = 'move-node-to-workspace A'
ctrl-alt-cmd-w = 'move-node-to-workspace W'
ctrl-alt-cmd-t = 'move-node-to-workspace T'
ctrl-alt-cmd-m = 'move-node-to-workspace M'
ctrl-alt-cmd-g = 'move-node-to-workspace G'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

# Disable "hide application" shortcuts
cmd-h = []
cmd-alt-h = []

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace T'
check-further-callbacks = true
