[window]
option_as_alt = "Both"

[font]
size = 17
normal.family = "UbuntuMono Nerd Font"
offset.x = 1

[selection]
save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#400f30"
foreground = "#f1f1f0"

[colors.cursor]
text = "#4c4c4c"
cursor = "#c7c7c7"

[colors.selection]
text = "#000000"
background = "#c1deff"

[colors.normal]
black   = "#3b4244"
red     = "#d81e00"
green   = "#5ba501"
yellow  = "#cfae00"
blue    = "#427ab3"
magenta = "#89658e"
cyan    = "#00a8aa"
white   = "#dbded8"

[colors.bright]
black   = "#686a66"
red     = "#f54235"
green   = "#99e343"
yellow  = "#fdeb61"
blue    = "#84b0d8"
magenta = "#bc94b7"
cyan    = "#37e6e8"
white   = "#f1f1f0"

[[hints.enabled]]
# copied from default, with modified `mouse.mods`
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
mouse.mods = "Command"
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
  # command+N opens new window in home directory
  { key = "N", mods = "Command", command = { program = "/Applications/Alacritty.app/Contents/MacOS/alacritty"} },
  # alt+left and alt+right move word-wise left/right
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
