[language-server.typos]
command = "typos-lsp"

[language-server.vale]
command = "vale-ls"

[[language]]
name = "git-commit"
language-servers = [
  "typos",
  "vale",
]
rulers = [73]

[[language]]
name = "markdown"
language-servers = [
  "marksman",
  "markdown-oxide",
  "typos",
  "vale",
]

[[language]]
name = "python"
rulers = [80]
text-width = 79
language-servers = [
  "pylsp",
  "typos",
  "vale"
]
